### ISSUE TITLE
Unexpected output of attendance

### ISSUE THREAD

**Issue by MisterCommand** [dmddjack/CityU_EE_SumSch_M2_Course#1]
Hello,
I ran your code in Python 3.7.0 and the output value of attendance seemed to be incorrect.

### Input values
```
population = 1
input student's name:A
input school name:A
does A absent at day 1?y
does A absent at day 2?y
does A absent at day 3?y
does A absent at day 4?n
```

### Output
student name | school name | SS_ID | Attendance
--- | --- | --- | ---
A | A | SS001 | (True,)

It seems like the value under "Attendance" will only "display" the last input (in this case, "does A absent at day 4?n")

### Possible cause
att=[] in for loop
```
    for j in range(1, 5):
        att = []
        while True:
            result = input('does %s absent at day %d?(y/n)' % (student[i], j))
            if result == 'y':
                att.append(False)
                break
            elif result == 'n':
                att.append(True)
                break
            else:
                print('invalid input')
```

Is this an expected output? 
Other than this minor issue, great code and advanced Python usage, I appreciate your hard work!

**Comment by shiyukfong** [comment]
Thanks for your Issue.
I have updated the code.
